name: Create unity package

on:
    push:
        tags: 
         - '*'
jobs:
    create-package:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: |
            echo "Assets/ARKit Create.cs.meta" > metalist
        - run: mkdir -p build

        - uses: pCYSl5EDgo/create-unitypackage@master
          with:
            package-path: 'build/ARKit-Create-${{github.ref_name}}.unitypackage'
            include-files: metalist
        - uses: actions/upload-artifact@master
          with:
            path: build/ARKit-Create-${{github.ref_name}}.unitypackage
            name: ARKit-Create-${{github.ref_name}}